version: '3.8'

services:
  app:
    container_name: snippet-nest-app
    build:
      context: .
      dockerfile: Dockerfile
      target: builder # Use the builder stage for development
    command: pnpm start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.dev
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    networks:
      - snippet-network
    restart: unless-stopped

  postgres:
    container_name: snippet-nest-postgres
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=snippets
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - snippet-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: snippet-nest-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - snippet-network
    restart: unless-stopped
    command: redis-server --appendonly yes

networks:
  snippet-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
